github: [zulfikriyahya]            # Username GitHub Sponsors kamu
# patreon: zulfikriyahya             # Username Patreon
# open_collective: attendancemachine
ko_fi: zulfikriyahya
# tidelift: npm/attendance-machine   # Misalnya kalau sudah publish ke npm
community_bridge: attendance-machine
# liberapay: zulfikriyahya
# issuehunt: zulfikriyahya
# lfx_crowdfunding: attendance-machine
# polar: zulfikriyahya
buy_me_a_coffee: zulfikriyahya
thanks_dev: zulfikriyahya
custom: ['https://saweria.co/zulfikriyahya', 'https://trakteer.id/zulfikriyahya']
